### ISSUE TITLE
Caching of ifort action not working on Windows

### ISSUE THREAD

**Issue by Hofer-Julian** [MODFLOW-USGS/modflow6#1054] opened 2022-09-27 10:41 UTC
Looking at this line and the time it takes I don't think the caching of ifort is working for our Windows CI at the moment: https://github.com/MODFLOW-USGS/modflow6/actions/runs/3113214744/jobs/5047564396#step:5:38

**Comment by w-bonelli** [comment] 2022-10-26 04:37
This [should be fixed](https://github.com/w-bonelli/modflow6/actions/runs/3326146929/jobs/5499570023#step:5:101) by the [last](https://github.com/modflowpy/install-intelfortran-action/pull/9) [couple](https://github.com/modflowpy/install-intelfortran-action/pull/12) updates to `modflowpy/install-intel-fortran@v1` but will wait to close until confirmed in this repo's CI

**Comment by w-bonelli** [comment] 2022-12-11 15:33
Tentatively addressed by https://github.com/modflowpy/install-intelfortran-action/pull/20, although key rotation is just a workaround and potential remains for the cache to break and stay broken for periods < 1 day.

I'm also considering adding a Windows job to this repo's nightly large model CI just to save the cache and allow commit-triggered builds to benefit from it for the rest of the day.

**Comment by w-bonelli** [comment] 2022-12-19 15:27
#1118 adds a nightly CI job to warm the cache. Will plan to close once confirmed on this repo ([example on my fork](https://github.com/w-bonelli/modflow6/actions/runs/3731673533/jobs/6330198779))

**Comment by w-bonelli** [comment] 2022-12-20 16:03
Looks like cache restore is finally working after the early morning warmup https://github.com/MODFLOW-USGS/modflow6/actions/runs/3741771804/jobs/6351859039#step:6:111

**Closed by w-bonelli** 2022-12-20 16:03 UTC
Labels: bug
