### ISSUE TITLE
Exception in UBDSV06

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#423] opened 2020-05-04 18:42 UTC
Hi Chris,

I get an unhandled exception in the above mentioned subroutine due to variable DIS being undefined.
Attached you find the call stack as a screenshot.
In case you need the model to reproduce the error, I'd have to send it some private way.

Best regards
Andreas
![UBDSV06_Exception](https://user-images.githubusercontent.com/13199371/81001273-c65c9580-8e47-11ea-90e6-d2a72509eef4.jpg)

**Comment by langevin-usgs** [comment] 2020-05-04 19:35
Sorry, @tandreasr, there is not much I can do with this screenshot.  Can you give a better idea of what the problem is, or which variable is the problem?  If not, then you could send the model to my usgs work email.

**Comment by tandreasr** [comment] 2020-05-05 04:09
Hi Chris,
I was able to reproduce the error with one of your test models.
The only adaption I've made is to add a BUDGET FILEOUT line to the mvr file.

[__test029.zip](https://github.com/MODFLOW-USGS/modflow6/files/4578871/__test029.zip)

What happens is that in subroutine save_flows() you reference dis which is undefinded for exchange movers between different models. Instead  you've obviously got the 2 different discretizations of the to models, which should be used instead.

But using the attached model you should be able to reproduce the error anyway.

Thanks
Andreas

**Comment by langevin-usgs** [comment] 2020-05-05 12:17
I'lll take a look.  Thanks for tracking it down and sending a simple model that demonstrates the problem!  Much appreciated.

**Comment by tandreasr** [comment] 2020-05-05 12:24
Re: [MODFLOW-USGS/modflow6] Exception in UBDSV06 (#423)



You're welcome :-)

**Comment by langevin-usgs** [comment] 2020-05-05 14:23
Should be fixed now.  Fortunately it was an easy fix.  Give it a go.

**Closed** 2020-05-05 14:22 UTC
