### ISSUE TITLE
Usage of RCH assignment to upper most active cell only works for unconfined conditions without NEWTON

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#927] opened 2022-04-06 15:02 UTC
Hi,

I’m running complex models in unconfined mode and find some troubles with the RCH. It seems like the automatic assignment of RCH to the upper active cell is not working as in the subroutine:

  **subroutine rch_cf(this, reset_mover)**

the following variable this%ibound(node) is 1 as it should be zero (according to my IDOMAIN-input.
 So, the following syntaxt does not change the layer to which the RCH needs to be assigned to.

      ! -- reset nodelist to highest active
      if (.not. this%fixed_cell) then
        if(this%ibound(node) == 0) &
          call this%dis%highest_active(node, this%ibound)
        this%nodelist(i) = node
      endif

Only in case  NEWTON is off and the wet-dry option is enabled, the IBOUND variabele is set to 0 correctly in the subroutine:

**subroutine sgwf_npf_wetdry(this, kiter, hnew)**

at

        if(this%ibound(n)<0) then
          errmsg = 'CONSTANT-HEAD CELL WENT DRY -- SIMULATION ABORTED'
          call store_error(errmsg)
          write(errmsg, fmttopbotthk) ttop,bbot,thck
          call store_error(errmsg)
          call this%dis%noder_to_string(n, nodestr)
          write(errmsg, fmtni) trim(adjustl(nodestr)), kiter, kstp, kper
          call store_error(errmsg)
          call this%parser%StoreErrorUnit()
        endif
        this%ibound(n)=0

However, my model does not converge and I want to use NEWTON, but even in confined conditions the layer assignment does not work. After to code-inspectation I noticed that the ibound becomes zero if permeability values are zero.

      ! -- Cycle if k11 is not zero
      if(this%k11(n) /= DZERO) cycle nodeloop

      !
      ! -- If this part of the loop is reached, then all connections have
      !    zero transmissivity, so convert to noflow.
>>      this%ibound(n) = 0
      this%hnew(n) = this%hnoflo
      if(this%irewet /= 0) this%wetdry(n) = DZERO
      call this%dis%noder_to_string(n, cellstr)
      write(this%iout, fmtcnv) trim(adjustl(cellstr))

However, in this MF6 version K11, K22 and K33 need to > 0 at all times, otherwise an error message appears.

    do n = 1, size(this%k11)
      if(this%k11(n) <= DZERO) then
        nerr = nerr + 1

So, I believe it is better to tricker whether ibound=0 on **(top-bot)*k11** rather than k11 only. I did not try it, but having k11<0 might be solving the issue however, according to the manual k11 needs to be > 0. 

Alternatively, why can IBOUND not be a copy of ABS(IDOMAIN).

Greetings,

Peter Vermeulen

Research Hydrologist (PhD) / iMOD Code Architect - Deltares
 
Unit Subsurface and Groundwater Systems (BGS)
Section Groundwater Management (GWB)
Daltonlaan 600 PO Box 85467 3508 AL Utrecht, The Netherlands
Phone: +31(0)6 3054 8234 Fax: +31(0)88 335 7856
Email: [peter.vermeulen@deltares.nl](mailto:peter.vermeulen@deltares.nl) Website: [www.deltares.nl](http://www.deltares.nl/)

**Comment by langevin-usgs** [comment] 2022-04-06 16:41
Hey @VermeulenPTM, I think this is a duplicate of #181.  Recharge behaves very differently for newton and non-newton (wetting/drying).  If you are using Newton, then IBOUND should be 1 for all cells, even if they are "dry" and the IBOUND value will remain as 1 throughout the simulation.  And in this Newton case, you assign recharge to the very top cell, and the heads in the dry cells will be calculated to pass that recharge down to the water table.  

IDOMAIN is something very different.  IDOMAIN means that the cell does not exist at all.  Cells with IDOMAIN values less than one are filtered out when we read the input data, so internally, we only store cells that actually "exist".  

Hope this helps!

**Closed by langevin-usgs** 2022-04-06 16:41 UTC

**Comment by VermeulenPTM** [comment] 2022-04-07 07:29
Hi Christian,

Thanks for your quick and helpful reply. Yes it will help and sounds logically too. Sorry, that this issue was passed by earlier, in 2019 already.

Greetings,
Peter
