### ISSUE TITLE
Concentrations Blow Up in Boundary Cells 

### ISSUE THREAD

**Issue by michelob23** [MODFLOW-USGS/modflow6#950] opened 2022-06-02 15:17 UTC
I'm using MODFLOW-6's GWT model. In a couple boundary cells (17, 63, 1) and (17, 62, 1), concentrations blow up (one positive, one negative). These are confined CHD cells with thickness ~700 m on the bottom corner of the model - the CHD value for these cells (~1800 m) is about 80m greater than the top elevation of the cells (~1720 m). These cells are far from any sources and no source/sink concentrations are specified with the CHD package. Removing the CHD from the bottom layer of the model fixes the problem - is there any other way to get rid of what appears to be random noise?

![conc_ts_17_63_1](https://user-images.githubusercontent.com/18356141/171660857-c117e63d-5681-4afc-bff6-33ee996e56f7.png)

![conc_ts_17_62_1](https://user-images.githubusercontent.com/18356141/171660863-2b3bdad1-6d46-48ce-abf4-c6a6b5ab9582.png)

![head_ts_17_63_2](https://user-images.githubusercontent.com/18356141/171662989-3f47e08d-cc4f-4ff8-ade5-b3b2bde9fb2a.png)

![head_ts_17_62_2](https://user-images.githubusercontent.com/18356141/171662995-e8d31342-328d-4921-a3bd-fbcbb819c8d0.png)

I zipped up a 7z file to get the model to upload: 
[model.7z.zip](https://github.com/MODFLOW-USGS/modflow6/files/8825118/model.7z.zip)

I got my Linux executable here: https://github.com/MODFLOW-USGS/executables

**Comment by langevin-usgs** [comment] 2022-06-08 19:14
I made a couple of runs today.  If I shut off the IMS COMPLEXITY option and comment out the dispersion package, then I do not get those large concentration changes in those two cells.  This is something that we can look at further on our, but maybe this will help you move forward for now.

**Comment by langevin-usgs** [comment] 2022-06-10 14:59
I've looked at this a little bit more, but don't have any real conclusions.  I am able to reproduce those strange concentrations in those cells.  I suppose it could be overshoot/undershoot due to dispersion, but that seems excessive and I suspect it is something else.  I don't see anything wrong in your input files.  I tried to reproduce this behavior with a simple model with constant heads in a lower layer, but the simple model behaves as expected.  I notice that you are using a value of 2.0 for TSMULT.  This results in extremely short time step lengths, and maybe there is a precision issue due to this?  If there was any way you could reproduce this with a smaller version of the model, I could run it through the debugger and see what's going on.  The current version of the model is too big.

**Comment by michelob23** [comment] 2022-06-10 21:41
Oh jeez this is embarrassing - looks like some initial heads made their way into the storage package.

**Comment by langevin-usgs** [comment] 2022-06-11 02:53
We appreciate you letting us know.  With a new capability like GWT we tend to think it's a bug in the code, but glad to hear that may not be the case here.  Am closing this issue.

Here's a view of the rogue plume in case you're interested.  

<img width="1591" alt="image" src="https://user-images.githubusercontent.com/3372403/173169884-48c66308-0bd3-4a90-a40e-9b5d95e86fb0.png">

**Closed by langevin-usgs** 2022-06-11 02:53 UTC

**Comment by michelob23** [comment] 2022-06-13 14:59
FYI - after correcting the STO package problem and doing some runs over the weekend, I do still get concentrations tending to +-1e10 along the CHD in the bottom layer. With the XT3D_OFF setting in the DSP package, however, this does not happen. I'm going to do some more runs to see if Flow Imbalance Correction might also be able to resolve the issue. 

[modflow_cr.sto.zip](https://github.com/MODFLOW-USGS/modflow6/files/8892177/modflow_cr.sto.zip)
