### ISSUE TITLE
Error checking on IDOMAIN<>1

### ISSUE THREAD

**Issue by VermeulenPTM** [MODFLOW-USGS/modflow6#928] opened 2022-04-07 07:25 UTC
Hi,

Question about the fact that the K11 needs to be > 0.0 for ABS(IDOMAIN) values of 1. Is there a particular reason for? Would it be an option to ignore all error checking for cells with IDOMAIN<>1? Most important reason is that inspecting model input raises questions about K11 or other values that are in fact dummy values.

Greetings,
Peter Vermeulen
Deltares - NLD

**Comment by langevin-usgs** [comment] 2022-04-07 12:16
A model should run fine if K11 is zero and either of the K values are positive.  But we've run into some problems when any of the K values are zero and the tensor is rotated.  In most cases a zero K value indicates an error in the preprocessing along the way, and so we've found that it is helpful to have this check.  Can you just specify 1e-10 or something similar so that the behavior is as intended?

**Comment by langevin-usgs** [comment] 2022-05-23 15:27
Closing as this is not really a bug in the code.  We can discuss further on this closed issue if there is interest.

**Closed by langevin-usgs** 2022-05-23 15:27 UTC
