### ISSUE TITLE
MODFLOW 6.3 crashes with LKT package.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/modflow6#1003] opened 2022-08-04 17:07 UTC
**Describe the bug**
With the attached model, MODFLOW 6 crashes without issuing an error report. The model runs normally if the LKT package is excluded.

**To Reproduce**
Run the attached model

**Expected behavior**
either the model would terminate normally or end with an error report

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version21H2
[LktBug.zip](https://github.com/MODFLOW-USGS/modflow6/files/9261799/LktBug.zip)

**Comment by langevin-usgs** [comment] 2022-08-04 18:26
@rbwinst-usgs, I ran this model with the develop version, and it terminates with this error message.  So I think this issue has been resolved:

```
                                   MODFLOW 6
                U.S. GEOLOGICAL SURVEY MODULAR HYDROLOGIC MODEL
                   VERSION 6.4.0 release candidate 03/04/2022
                               ***DEVELOP MODE***

   MODFLOW 6 compiled Jul 21 2022 14:59:33 with Intel(R) Fortran Intel(R) 64
   Compiler Classic for applications running on Intel(R) 64, Version 2021.6.0
                             Build 20220226_000000

This software is preliminary or provisional and is subject to
revision. It is being provided to meet the need for timely best
science. The software has not received final approval by the U.S.
Geological Survey (USGS). No warranty, expressed or implied, is made
by the USGS or the U.S. Government as to the functionality of the
software and related material nor shall the fact of release
constitute any such warranty. The software is provided on the
condition that neither the USGS nor the U.S. Government shall be held
liable for any damages resulting from the authorized or unauthorized
use of the software.


 Run start date and time (yyyy/mm/dd hh:mm:ss): 2022/08/04 13:24:42

 Writing simulation list file: mfsim.lst
 Using Simulation name file: mfsim.nam


ERROR REPORT:

  1. Problem with GWF-GWT exchange GWF-GWT_1.  The GWF model must be solved
     by a different IMS than the GWT model. Furthermore, the IMS specified
     for GWF must be listed in mfsim.nam before the IMS for GWT.
```

**Comment by langevin-usgs** [comment] 2022-08-04 18:31
Duplicate of #946.

**Closed by langevin-usgs** 2022-08-04 18:31 UTC
Labels: bug, duplicate
