### ISSUE TITLE
Troubles with segmented evapotranspiration in MF6(continued)

### ISSUE THREAD

**Issue by sebmeng** [MODFLOW-USGS/modflow6#938] opened 2022-05-05 15:42 UTC
reference: #930 
Hey, @langevin-usgs  I've been doing some tests with the recommendations that you gave me, but I still have this problem. I still think that MF6 might have some issues with evapotranspiration with more than two segments. I've attached the files if you want to take a look (MF6 and MFUSG models with 6 evapotranspiration segments). 
Thank you in advance for your help!

Regards
[Test.zip](https://github.com/MODFLOW-USGS/modflow6/files/8632638/Test.zip)

**Comment by langevin-usgs** [comment] 2022-05-10 19:24
Hi @sebmeng, I took a look at your model, and I think there may be a mistake in your EVT input.  As an example, I pulled the first record out of your EVT input file.  I think this is how you have ordered your columns:

```
cellid 1  
surface 2300.000000  
rate 4.640000e-03  
depth 2.000000  
pxdp-A 1.300000e-02  
petm-A 9.920000e-01    
pxdp-B 2.500000e-02  
petm-B 4.820000e-01  
pxdp-C 5.500000e-02  
petm-C 1.980000e-01    
pxdp-D 1.000000e-01  
petm-D 8.500000e-02    
pxdp-F 2.000000e-01  
petm-F 3.700000e-02
```

I think the issue is that you are providing (pxdp, pets)_A, (pxdp, pets)_B, (pxdp, pets)_C and so forth.  MODFLOW 6 is expecting all pxdp and then all pets to be together.  So you need to provide pxdp_A, pxdp_B, pxdp_C and then petm_A, petm_B, petm_C, ...  

Thus, your input should be in this order instead:

```
cellid 1  
surface 2300.000000  
rate 4.640000e-03  
depth 2.000000  
pxdp-A 1.300000e-02  
pxdp-B 2.500000e-02  
pxdp-C 5.500000e-02  
pxdp-D 1.000000e-01  
pxdp-F 2.000000e-01  
petm-A 9.920000e-01    
petm-B 4.820000e-01  
petm-C 1.980000e-01    
petm-D 8.500000e-02    
petm-F 3.700000e-02
```

Let us know if this explains the problem.

**Comment by sebmeng** [comment] 2022-05-12 22:02
Hi @langevin-usgs, changed the order of the EVT package input as you recommended:
The original columns were the following:

![image](https://user-images.githubusercontent.com/48210348/168150597-9bd098e5-f341-4cbb-bbce-bc5de1590a48.png)

Now, rearranged:
![image](https://user-images.githubusercontent.com/48210348/168150711-fbd4f783-c811-4935-93aa-65e5ec9043b2.png)

But I still had convergence problems, and the difference between USG and MF6 model is maintained as well. I reordered with the information of the deepest segment first, and it worked!:

![image](https://user-images.githubusercontent.com/48210348/168172520-51f41b85-43a1-4fa5-a888-c5914e6e73c3.png)

Now I have no convergence problems and the results are similar to MFUSG. Thank you for your valuable help! And for taking the time to check the files I've sent (I'm sending the EVT file that works),

Kind regards!
[gv14_3.zip](https://github.com/MODFLOW-USGS/modflow6/files/8682817/gv14_3.zip)

**Comment by langevin-usgs** [comment] 2022-05-12 23:42
Hi @sebmeng, I'm glad to hear that some progress is being made.  I am, however, concerned by the steps that you had to take in order to get this to work correctly.  I'm pretty sure that PXDP needs to be sorted from lowest value to highest value.  I double-checked this in the code and in the previous ETS package, upon which the MODFLOW 6 EVT package is based.  The online guide for MODFLOW for the ETS packages also supports this ascending order requirement for PXDP (https://water.usgs.gov/ogw/modflow/MODFLOW-2005-Guide/ets.html).  If this order is reversed, I can see why you would get an answer that appears to be valid, but what I think is happening is that the ET rate is being calculated using the wrong segment.  I will check this again tomorrow, but you might want to check things on your end again.  The code is clearly designed to work from the surface downward toward the extinction depth, which means PXDP should be in ascending order.  It's possible there is a problem in the mf6 code, and I will check that, but I'm thinking something is smoldering somewhere on your end.  BTW, MODFLOW-USG would also require PXDP to be specified in ascending order.

**Comment by langevin-usgs** [comment] 2022-05-13 12:26
Hi @sebmeng, I ran some tests this morning and feel confident that PXDP needs to be listed in ascending order and that the segmented ET function is implemented correctly in MODFLOW 6.  We also added a new check to MODFLOW that will cause the program to terminate if PXDP is not listed in ascending order.  I will close this issue for now.  Let us know if you find something different.

**Closed by langevin-usgs** 2022-05-13 12:26 UTC
