### ISSUE TITLE
Problem of Solving saturated hydrostatic problem with Saturation = 1

### ISSUE THREAD

**Issue by ougx** [MODFLOW-USGS/modflow6#943] opened 2022-05-23 17:34 UTC
My 1D column example starts with saturated hydrostatic condition (Saturation = 1), only boundary condition is the flux at the end of the column.

This seems to create a singular matrix. The problem can be reproduced as follows:

```python
import flopy
import numpy as np

nlay = 1
nrow = 1
ncol = 10
thick = 1
dx = 1
dy = 1
wellrate = 1
k = 1000

modelname = 'hydrostatic'

botm = np.ones([nlay, nrow, ncol])
for i in range(nlay):
    botm[i] = thick * (nlay - i - 1)

hk = np.ones([nlay, nrow, ncol])
hk.fill(k)

sim = flopy.mf6.MFSimulation()
tdis = flopy.mf6.ModflowTdis(sim, perioddata=[[1, 1, 1.]])
gwf = flopy.mf6.MFModel(sim, model_type='gwf6', modelname=modelname, )
gwf.name_file.newtonoptions = "NEWTON UNDER_RELAXATION"

dis = flopy.mf6.ModflowGwfdis(gwf, nlay=nlay, nrow=nrow, ncol=ncol, delr=dx, delc=dy, top=thick*nlay, botm=botm)
npf = flopy.mf6.ModflowGwfnpf(gwf, icelltype=1, k=hk, k33=hk)
sto = flopy.mf6.ModflowGwfsto(gwf, iconvert=1, ss=0.0, sy=0.35, steady_state={0: False})
wel = flopy.mf6.ModflowGwfwel(gwf, stress_period_data=[[(nlay-1,nrow-1,ncol-1), -wellrate]])
ic  = flopy.mf6.ModflowGwfic(gwf, strt=nlay,)
ims = flopy.mf6.ModflowIms(sim, print_option='all', outer_dvclose=1e-4, linear_acceleration="BICGSTAB", rcloserecord=np.abs(wellrate/10))
sim.register_ims_package(ims, modelname)
sim.write_simulation()
```

**Comment by jdhughes-usgs** [comment] 2022-05-23 18:30
Since you are starting the simulation at saturation and have specified storage to be zero no storage term is added to the diagonal during the first formulate step. This is the source of the singular matrix issue. Adding a small specific storage value will correct this problem. I specified a specific storage value of 1e-12 and the simulation converged for me.

This is not a bug. Closing this issue.

**Closed by jdhughes-usgs** 2022-05-23 18:30 UTC
