### ISSUE TITLE
Observation utility for GWT with boundary conditions specified through SSM using the "aux variable" method

### ISSUE THREAD

**Issue by RyanConway91** [MODFLOW-USGS/modflow6#1020] opened 2022-08-24 15:15 UTC
I have a model with concentrations specified using the "AUX variable" method for RIV, CHD, and RCH. I am using BOUNDNAMES

I want an observation that is the solute mass flux rate into each BOUNDNAME during the transport model. The only way I can currently see to get at this (without cracking open the .cbt file) is to break every BOUNDNAME into its own package and look at the mass balance in the .lst file.

Why is there no obs utility for the SSM?

**Comment by langevin-usgs** [comment] 2022-08-24 15:21
Duplicate of #1014.

Hasn't been implemented yet.  It's on the list.

**Comment by langevin-usgs** [comment] 2023-06-22 12:21
Added to feature request list.

**Closed by langevin-usgs** 2023-06-22 12:21 UTC
Labels: duplicate, enhancement
