### ISSUE TITLE
Nightly build broken

### ISSUE THREAD

**Issue by Hofer-Julian** [MODFLOW-USGS/modflow6#1269] opened 2023-06-23 07:39 UTC
It seems like https://github.com/MODFLOW-USGS/modflow6-nightly-build/pull/34 broke the nightly builds.
At least the latest release has no binaries anymore: https://github.com/MODFLOW-USGS/modflow6-nightly-build/releases/tag/20230623

**Comment by mwtoews** [comment] 2023-06-23 08:38
See https://github.com/modflowpy/flopy/pull/1837

**Comment by w-bonelli** [comment] 2023-06-23 21:21
This was caused by recent CI work, fixed by https://github.com/MODFLOW-USGS/modflow6-nightly-build/commit/0bcdda5c2f267e7947855c301727dda41dcd2a7c. It is a consequence of both repos using `release.yml`

Note distribution names on the nightly build changed to `mf6.y.zdev_ostag`, and upcoming releases here will have assets with similar names minus "dev" i.e. adding "_win64" to the windows archive, in an effort to standardize the various distributions

**Closed** 2023-06-23 22:01 UTC
Labels: bug
