### ISSUE TITLE
Error in refactored CSV output

### ISSUE THREAD

**Issue by tandreasr** [MODFLOW-USGS/modflow6#410] opened 2020-04-21 13:18 UTC
Hi,
thanks for adapting the CSV output as requested.
Unfortunately the latest developer snapshot contained errors.
I've attached the corrected NumericalSolution.f90 for reference.

[NumericalSolution.zip](https://github.com/MODFLOW-USGS/modflow6/files/4510192/NumericalSolution.zip)
Best regards
Andreas

**Comment by jdhughes-usgs** [comment] 2020-04-21 14:00
What is the error condition that occurs? Can you provide a small test model that demonstrates the error?

**Comment by tandreasr** [comment] 2020-04-21 17:59
Hi,
it's actually one of your test cases (test011_mflgr_ex3_sfr sligthly modified and attached).
The problem is that the CSV output for inner iterations is correct for the first outer iteration only of every time step. Succeeding outer iterations are incorrect inside MFSIM.IMS.INNER_1.CSV, because the values of outer iter 1 are repeated (the list file output however is correct).
I've already corrected my sources - that's why I can't easily send you the wrong CSV.
Just start the testcase in order to reproduce the behaviour.

[__testcase.zip](https://github.com/MODFLOW-USGS/modflow6/files/4511713/__testcase.zip)

**Comment by jdhughes-usgs** [comment] 2020-05-26 14:44
I can't reproduce what you found with `test011_mflgr_ex3_sfr` with the latest develop branch source code. I modified `ex3_parent.ims` as you did to save inner and outer convergence information. I ran it on both `OSX` and `Windows 10` (compiled with gfortran and Intel, respectively) but the inner and outer iteration information is correct. 

![image](https://user-images.githubusercontent.com/2073498/82914511-9a5f9c00-9f3d-11ea-8567-a6743ca9f807.png)

I am closing this issue but will reopen it if you can provide additional information that makes it possible to reproduce the error.

**Comment by tandreasr** [comment] 2020-05-27 08:12
Hi,
from what I see from your CSV output it isn't correct.
For nouter=2 the values of its 20 rows are identical to the first 20 rows of nouter=1
For nouter=3 the same happens and so forth.
To summarize: the number of rows written for each outer iter is correct,
but the actual values written (columns solution_inner_dvmax ff.) are just taken from nouter=1
Regards,
Andreas

**Comment by jdhughes-usgs** [comment] 2020-05-27 16:28
A better initial description of the specific error would have been helpful (i.e., the dvmax values are incorrect for outer iterations 2 ... nouter). I was thinking that you were reporting an error in the inner iteration count column. Will address the issue now. Thanks for the error report.

**Closed** 2020-05-27 23:56 UTC
